services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    env_file:
      - .env.production
    depends_on:
      - postgres
      - redis
    networks:
      - deathmatch.net
    restart: always

  redis:
    container_name: redis
    image: redis:alpine
    env_file:
      - .env.production
    networks:
      - deathmatch.net
    ports:
      - 6379:6379

  postgres:
    container_name: postgres
    image: postgres:15.2
    env_file:
      - .env.production
    networks:
      - deathmatch.net
    ports:
      - 5432:5432
    environment:
       PG_DATA: /var/lib/postgresql/data
    volumes:
       - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:

networks:
  deathmatch.net:
    name: deathmatch.net
    external: true